backend:
  name: github
  branch: upgrade
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: content/img
public_folder: /img

local_backend: true

collections:
  - name: "projects"
    label: "Project"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Project Date", name: "date", widget: "datetime"}
      - {label: "Grid image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Participants", name: "participants", widget: "text", required: false}
      - {
        "label": "Images",
        "name": "galleryImages",
        "widget": "list",
        "field": {
          "label": "Image",
          "name": "image",
          "widget": "image"
        }
      }
      - {label: "Photo credits", name: "credits", widget: "string", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/impressum/index.md"
        label: "Impressum"
        name: "impressum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
