version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "live"
    allow:
      - dependency-type: "direct"
        update-types: ["security"]
      - dependency-type: "indirect"
        update-types: ["security"]
    automerge:
      vulnerability-alerts: true
      updates: in_range
    versioning-strategy: widen-ranges
    groups:
      gatsby:
        dependencies:
          - "gatsby-*"
        exclude-patterns:
          - "gatsby-remark-embed-youtube"
          - "gatsby-remark-relative-images-v2"
